CREATE DATABASE IF NOT EXISTS itsm_identity;
CREATE DATABASE IF NOT EXISTS itsm_incident;
CREATE DATABASE IF NOT EXISTS itsm_change;
CREATE DATABASE IF NOT EXISTS itsm_asset;
CREATE DATABASE IF NOT EXISTS itsm_notification;
